# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='model_desc',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='parent_model_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='model_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
