# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20160423_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='parent_model_id',
        ),
        migrations.AddField(
            model_name='testmodel',
            name='path',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
